### ISSUE TITLE
About ssl problem

### ISSUE THREAD

**Issue by ZgrK** [talkingaboutthis/woo-rapido#1]
After installing plugin then my wordpress admin page give some console error

<img width="1416" alt="screen shot 2018-01-25 at 15 57 48_927" src="https://user-images.githubusercontent.com/879674/35416519-049effc6-0232-11e8-91a2-804aff019e77.png">

Then try to search solution on here https://github.com/talkingaboutthis/woo-rapido/blob/05b0143448e81acd74f8a80de10766bdafd90b42/includes/init.php#L62 it's must be change with 'http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css' to '//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css' working with http and https sites without any problem.

**Comment by boyanraichev** [comment]
thanks a lot for this!
